### ISSUE TITLE
Sigue activa la idea?

### ISSUE THREAD

**Issue by SidVal** [laneros/migracion-discourse#1]
Hola @JulianD ! No sabía que eras de Laneros :+1: 

¿Sigue en pié esta idea de migrar a Discourse?

Quería rescatar mis opiniones...

## [Caracteristicas](https://github.com/laneros/migracion-discourse/blob/master/docs/CARACTERISTICAS.md)

* ¿Qué es "User Upgrades"? No entiendo qué sería. Disculpa mi ignorancia.
* Tapatalk: esto existe solo para foros no responsives. Lo conozco por experiencia, y como bien dices es horrible depender de este plugin. Yo creo que con Discourse no vas a necesitar Tapatalk., los usuarios hasta podrían tener una app "dedicada" a tu foro (ver [iOS](https://meta.discourse.org/t/beta-testing-the-ios-mobile-app/49662) o [Android](https://meta.discourse.org/t/beta-testing-the-android-mobile-app/50165)), sin necesidad de que desarrolles nada. Sería opcional, ya que Discourse es 100% responsive. 

## [Hosting](https://github.com/laneros/migracion-discourse/blob/master/docs/HOSTING.md)
Si necesitas uno con buen soporte, y de 10 dólares por mes o 100 al año, me avisas.

## [Plugins](https://github.com/laneros/migracion-discourse/blob/master/docs/PLUGINS.md)
Me llama la atención la cantidad de plugins. Mi consejo: solo pon los imprescindibles. Los demás, a la basura directo. Te ahorrarás dolores de cabeza, y aumentará la velocidad de carga de todo el foro.
Algunas observaciones:

* Cakeday >> no es de gamificación. La gamificación está ya en el "core" de Discourse. El cakeday solo felicita a los usuarios si cumplen años, o aniversarios. A mi modo de ver, no es imprescindible.
* Push Notifications >> No es necesario plugin. Ya avisa si te responden... 
* Presence >> No es necesario

## [Redirección](https://github.com/laneros/migracion-discourse/blob/master/docs/REDIRECCION.md)
Cuando hablas del Sitemap, te referis a la cuestión de agregar el sitemap a GWT? (Google Wembaster Tools). Si es por eso, no necesitas plugin alguno, podes hacerlo vía el /latest.rss y los distintos rss que carga Discourse automáticamente.

Lo demás, yo recomiendo redireccionar con NGINX

***
Saludos desde Argentina :argentina:

**Comment by JulianD** [comment]
Hola @SidVal. Muchas gracias por tus comentarios. Nunca creí que alguien se diera cuenta de ellos pues en laneros hay pocos desarrolladores que me sigan en github y tampoco he dado a conocer estas propuestas.

Si, vengo de vBulletin y XenForo pero últimamente me han entrado las ganas de ser más abierto con lo que hago y desarrollo en mis proyectos. Es por eso que quiero migrar a una plataforma abierta como Discourse y compartir lo que desarrolle o documente al respecto. 

Como no estoy trabajando 100% de mi tiempo en esta migración pues no había tenido tiempo de actualizar mi progreso. Actualmente estaba trabajando en mejorar el importador actual pero estaba encontrándome con muchos problemas en el tiempo de migración. Los solos usuarios me demoraron 24 horas en completarse en mi máquina local y faltaban los posts, adjuntos y mensajes privados entre otras cosas... Pero está semana vi lo nuevo del bulk importer y estoy trabajando precisamente en el bulk importer para XenForo.

Los User Upgrades es el término de XenForo para las suscripciones pagas. Hay un plugin de un ruso creo para discourse que hace algo similar y es gpl por lo que creo que podría ser un buen comienzo para desarrollar una solución de ese tipo pues es uno de los métodos de monetización que utilizamos.

Con el Tapatalk estoy de acuerdo contigo. Es una pesadilla mantener eso además que es un tráfico que no es nuestro precisamente. Lo que más busca la gente es obviamente las push notifications pero creo que también les gusta sentir que están utilizando una app nativa. Yo últimamente he usado mucho el sitio móvil de discourse y aunque es muy bueno, aún hay cosas le faltan para competir de frente con una app nativa. Sin embargo tampoco es imposible lograrlo. No sé si has visto el nuevo sitio móvil de Twitter que en mi opinión es el mejor ejemplo de lo que debe ser un sitio web móvil con todos sus conceptos de Progressive Web App, aunque en algunas funciones aún se queda corto (intenta cambiar tu avatar utilizando la opción de Crop y entenderás lo que digo) pero es casi perfecto en mi opinión. Si te soy sincero, este es un punto que me preocupa porque muchos usuarios ya no visitan mi sitio web sino que tienen la aplicación de Tapatalk instalada y si de la noche a la mañana deja de trabajar pues algunos lamentablemente dejarán de entrar. Es un riesgo que estoy dispuesto a tomar pero sé que es para bien.

Lo otro que me preocupa mucho es la redirección de las URL de XenForo a Discourse. Tengo algunas ideas que quiero probar. Lo primero es intentar de que el id en XenForo sea el mismo que en Discourse, esto permitiría mucho más fácil el redirect usando solo Nginx pero sé que no es una opción fácil. Lo otro es crear un script de redirección que consulte el ID viejo de la importación para saber el nuevo y haga el trabajo. Lo tercero es utilizar la función de Permalink de Discourse para agregar los diferentes permalinks pero teniendo 220k+ topics pues no sé qué tan bien sea el rendimiento con esa cantidad de permalinks. Ya lo veremos.

Respecto a Hosting, en el corto plazo aún no me preocupo. Tengo todavía algunos créditos de AWS que me durarán hasta comienzos de 2018. A partir de ahí no sé que hacer pues nunca he tenido una app de rails con más de 10k visitas al mes de tráfico entonces no sabría qué recursos necesitaría. Creería que un Linode de 12GB y 6 cores será suficiente pero hasta no probar no lo sabré.

En cuanto a los plugins, por ahora simplemente estoy armando una lista de posibles candidatos para tener. Hay ciertas cosas básicas que necesito como lo son el de suscripciones pagas, afiliados y ads pues componen toda la monetización del sitio. Otros como el spoiler tag los usuarios los han adoptado en muchos de los foros. Tengo otras necesidades que espero cubrirlas con el core de Discourse pero muy posiblemente me toque desarrollar bastante antes de hacer el switch completo.

Gracias por tus comentarios. Cuéntame más sobre tus proyectos y cómo estás involucrado con Discourse. Te veo muy activo en la parte de traducción y eso es un tema bien interesante, sobre todo por la cantidad de términos que se vuelven un problema traducir a nuestro idioma.

Saludos y mil gracias por tus aportes.

**Comment by SidVal** [comment]
>vengo de vBulletin y XenForo ...

Yo pasé por phpbb, invision, vbulletin, luego mybb, y ante inestabilidad volví a IPB.
Luego con los años vi que era aburrido el formato, y cuando ví Discourse... quedé shoqueado. Y decidí mudar como sea para ese lado.

> (...) este es un punto que me preocupa porque muchos usuarios ya no visitan mi sitio web sino que tienen la aplicación de Tapatalk instalada (...)

Debes despreocuparte por eso. Tapatalk a mi modo de ver tiene sus días contados. 
Los laneros tienen que entenderlo, el mundo cambia y progresa. :smile:  

> (...) Cuéntame más sobre tus proyectos y cómo estás involucrado con Discourse. Te veo muy activo en la parte de traducción y eso es un tema bien interesante, sobre todo por la cantidad de términos que se vuelven un problema traducir a nuestro idioma.

Sí, no sé, lentamente me voy animando a ayudarles a los de Discourse. Ellos han hecho muchísimo y me da cosa que no haya versiones traducidas. 

Ni recuerdo como llegué a Discourse.

Si necesitas algo, una mano de testing, lo que sea, avisa... sin compromiso.
Saludos
